apiVersion: v1
kind: Pod
metadata: 
  name: pod-1
  labels:
    component: web
spec:
  containers:
    - name: client
      image: sharma1612harshit/basic-node-app
      ports:
        - containerPort: 8080
