name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        echo "Github actions triggered"
        echo "Branch Name: ${GITHUB_REF##*/}"
        echo "-----"
        echo "Terraform setup"
        echo "-----"
        #sudo apt-get install unzip
        #wget https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip
        #unzip terraform_0.12.7_linux_amd64.zip
        #sudo mv terraform /usr/local/bin/
        terraform --version
        echo "-----"i
        echo "test ended"
